---
k3s_version: v1.25.5+k3s2
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3s_masters'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""