---
- name: Create a directory for docker volumes if it does not exist
  ansible.builtin.file:
    path: /root/docker_volumes/cups
    state: directory
    mode: "0755"

- name: Docker run cups
  community.docker.docker_container:
    name: cups
    image: "anujdatar/cups:latest"
    pull: true
    state: started
    recreate: true
    network_mode: host
    devices:
      - "/dev/bus/usb"
    restart_policy: "always"
    env:
      CUPSADMIN: admin
      CUPSPASSWORD: "{{ cups_password }}"
      TZ: "Europe/Amsterdam"
    volumes:
      - /root/docker_volumes/cups:/etc/cups
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
