---
- name: Read bitnami-sealed-secret-customkeys template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "bitnami-sealed-secret-customkeys-2.yaml.j2"
  when: sealed_secret_customkeys_2_tls_key is defined

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml
  when: '"github" in item.source'

- name: Validate if pod is ready | {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - "name=sealed-secrets-controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
