---
- name: Install usual apt packages
  ansible.builtin.import_tasks: install_apt_packages.yaml

# - name: Intall Python packages
#   ansible.builtin.import_tasks: install_python_packages.yaml

- name: Intall snap store packages
  ansible.builtin.import_tasks: install_snap_packages.yaml

- name: Unintall usual apt packages
  ansible.builtin.import_tasks: uninstall_apt_packages.yaml

- name: Intall ArgoCD CLI
  ansible.builtin.import_tasks: install_argocd-cli.yaml

- name: Intall kubectl
  ansible.builtin.import_tasks: install_kubectl.yaml
