---
- name: Include bare task
  ansible.builtin.include_tasks: bare.yaml

- name: Deploy | {{ argocd.name }}
  ansible.builtin.include_tasks: "argocd-core.yaml"
  when: argocd.deploy

- name: Deploy | {{ kube_vip.name }}
  ansible.builtin.include_tasks: "{{ kube_vip.name }}.yaml"
  when: kube_vip.deploy

- name: Deploy | {{ sealed_secrets.name }}
  ansible.builtin.include_tasks: "{{ sealed_secrets.name }}.yaml"
  when: sealed_secrets.deploy

- name: Deploy | {{ democratic_csi_manual.name }}
  ansible.builtin.include_tasks: "{{ democratic_csi_manual.name }}-manual.yaml"
  when: democratic_csi_manual.deploy

- name: Deploy | TLS certs
  ansible.builtin.include_tasks: tls-certificates.yaml

- name: Deploy | GitHub registry credentials
  ansible.builtin.include_tasks: github-registry-credentials.yaml

- name: Deploy | {{ ingress_nginx.name }}
  ansible.builtin.include_tasks: "{{ ingress_nginx.name }}.yaml"
  when: ingress_nginx.deploy

- name: Deploy | {{ node_feature_discovery.name }}
  ansible.builtin.include_tasks: "{{ node_feature_discovery.name }}.yaml"
  when: node_feature_discovery.deploy
